# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'localfood' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for localfood
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'SwiftyJSON'

  target 'localfoodTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'localfoodUITests' do
    # Pods for testing
  end

end
